import fs from 'fs'; import path from 'path';
const AGENTS_DIR = path.join(process.cwd(),'agents');
const FILE_MAP:Record<string,string>={soul_md:'SOUL.md',agents_md:'AGENTS.md',tools_md:'TOOLS.md',memory_md:'MEMORY.md'};
export class SharedFileSymlinkError extends Error{public readonly column:string;public readonly filename:string;public readonly agentName:string;constructor(agentName:string,column:string,filename:string){super(`Refusing to write shared file through a symbolic link: agent "${agentName}" column "${column}" -> "${filename}" is a symlink. Shared files (AGENTS.md, TOOLS.md) must be edited in agents/_shared/, not through a single agent's directory.`);this.name='SharedFileSymlinkError';this.column=column;this.filename=filename;this.agentName=agentName}}
const SHARED_COLUMNS=new Set(['agents_md','tools_md']);
function isSymlink(fp:string):boolean{try{return fs.lstatSync(fp).isSymbolicLink()}catch{return false}}
export function checkSharedFileSymlink(name:string,column:string):boolean{if(!SHARED_COLUMNS.has(column))return false;const d=agentDir(name);const fn=FILE_MAP[column];if(!fn)return false;return isSymlink(path.join(d,fn))}
export function agentSlug(n:string):string{return n.toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'')}
export function agentDir(n:string):string{return path.join(AGENTS_DIR,agentSlug(n))}
export function readAgentFiles(n:string):Record<string,string|null>{const d=agentDir(n);const r:Record<string,string|null>={};for(const[c,fn]of Object.entries(FILE_MAP)){const fp=path.join(d,fn);try{if(fs.existsSync(fp))r[c]=fs.readFileSync(fp,'utf-8');else r[c]=null}catch{r[c]=null}}return r}
export function writeAgentFile(n:string,c:string,ct:string):void{const d=agentDir(n);const fn=FILE_MAP[c];if(!fn)return;const tp=path.join(d,fn);if(SHARED_COLUMNS.has(c)&&isSymlink(tp))throw new SharedFileSymlinkError(n,c,fn);if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true});fs.writeFileSync(tp,ct,'utf-8')}
export function writeAgentDailyLog(n:string,dt:string,ct:string):void{const d=path.join(agentDir(n),'memory');if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,`${dt}.md`),ct,'utf-8')}
export function readAgentDailyLog(n:string,dt:string):string|null{const fp=path.join(agentDir(n),'memory',`${dt}.md`);try{if(fs.existsSync(fp))return fs.readFileSync(fp,'utf-8')}catch{}return null}
export function listAgentDailyLogs(n:string):string[]{const d=path.join(agentDir(n),'memory');try{if(fs.existsSync(d))return fs.readdirSync(d).filter(f=>f.endsWith('.md')).map(f=>f.replace('.md','')).sort().reverse()}catch{}return[]}
export function createAgentFolder(n:string,rl:string,md:string):void{const d=agentDir(n);const md2=path.join(d,'memory');fs.mkdirSync(md2,{recursive:true});let t='Execution';if(md.includes('opus'))t='Strategic';else if(md.includes('perplexity'))t='Research';const tps:Record<string,string>={'SOUL.md':`# ${n}\n\n## Identity\n- **Role:** ${rl}\n- **Model:** ${md}\n- **Tier:** ${t}\n\n## Personality\nDefine this personality, communication style, and values here.\n\n## Boundaries\nWhat this agent should and should not do.\n`,'AGENTS.md':`# ${n} - Workspace Rules\n\n## Role\n${rl}\n\n## Rules\n- Follow instructions precisely\n- Report completion with evidence\n- Escalate blockers to Master Orchestrator\n`,'TOOLS.md':`# ${n} - Tools & Capabilities\n\n## Available Tools\nList the tools, APIs, and integrations this agent has access to.\n\n## Credentials\nReference any API keys or credentials this agent needs (do not store secrets here).\n`,'MEMORY.md':`# ${n} - Long-Term Memory\n\n## Lessons Learned\nCurated memories, decisions, and lessons learned over time.\n\n## Key Decisions\nImportant decisions that should persist across sessions.\n`};for(const[fn,ct]of Object.entries(tps)){const fp=path.join(d,fn);if(isSymlink(fp))continue;if(!fs.existsSync(fp))fs.writeFileSync(fp,ct,'utf-8')}}
export function deleteAgentFolder(n:string):boolean{const d=agentDir(n);if(fs.existsSync(d)){fs.rmSync(d,{recursive:true});return true}return false}
export function ensureAgentsDir():void{if(!fs.existsSync(AGENTS_DIR))fs.mkdirSync(AGENTS_DIR,{recursive:true})}
