/**
 * P5-01 (c) steps 3-4 + (e) responsive proof.
 *
 * FAIL-FIRST, against a REAL server (mirrors create-task.spec.ts /
 * interview-lock.spec.ts): playwright.my-ai-ceo.config.ts's webServer stands
 * up its own `next dev` against a throwaway DB + workspace with the
 * interview shell-lock pre-satisfied, so this suite never has to guess
 * whether something happens to be listening on :4000 — it boots its own
 * server and FAILS (not skips) if that server never comes up.
 *
 * Captures committed screenshots (tests/integration/__screenshots__/
 * my-ai-ceo-responsive/) of the My AI CEO chat, the board, and the TaskModal
 * at the three breakpoints (360 / 768 / 1280), asserts ZERO horizontal body
 * scroll at each, and writes a violation catalog (VIOLATIONS.md in the same
 * directory) recording the pass/fail result for every surface x breakpoint
 * pair — the exact "responsive proof" the QC (e) list requires, and the
 * cataloging harness step 4 calls for (screenshots + a violation record).
 *
 * The board leg additionally proves the step-4 board mobile-responsiveness
 * QC finding: below `lg` the columns render as a horizontally-scrollable
 * strip plus a column picker, not the old full-width vertical stack.
 *
 * Run with: npm run test:e2e:my-ai-ceo
 */
import fs from 'fs';
import { test, expect, request, type Page } from 'playwright/test';
import { BASE_URL, PROOF_DIR } from './my-ai-ceo-responsive.fixture';

const BREAKPOINTS = [
  { name: '360-mobile', width: 360, height: 780 },
  { name: '768-tablet', width: 768, height: 1024 },
  { name: '1280-desktop', width: 1280, height: 900 },
];

type Verdict = { surface: string; breakpoint: string; width: number; hasHorizontalScroll: boolean; screenshot: string };
const catalog: Verdict[] = [];

test.beforeAll(async () => {
  const probe = await request.newContext({ baseURL: BASE_URL });
  try {
    const res = await probe.get('/api/health', { timeout: 10_000 });
    expect(res.ok(), `dev server not reachable at ${BASE_URL}/api/health`).toBeTruthy();
  } finally {
    await probe.dispose();
  }
});

/**
 * Writes the violation catalog once every test has recorded its verdict.
 * afterAll runs even if individual tests fail, so a real regression still
 * lands in the committed catalog instead of leaving it silently stale.
 */
test.afterAll(async () => {
  const rows = catalog
    .sort((a, b) => a.surface.localeCompare(b.surface) || a.width - b.width)
    .map(
      (v) =>
        `| ${v.surface} | ${v.breakpoint} | ${v.hasHorizontalScroll ? 'VIOLATION — horizontal body scroll' : 'clean'} | \`${v.screenshot}\` |`,
    )
    .join('\n');
  const violationCount = catalog.filter((v) => v.hasHorizontalScroll).length;
  const body = `# My AI CEO responsive violation catalog (P5-01)

Generated by \`tests/integration/my-ai-ceo-responsive.spec.ts\` against a live
\`next dev\` server (playwright.my-ai-ceo.config.ts's webServer). Regenerate
with \`npm run test:e2e:my-ai-ceo\`.

Surfaces: My AI CEO chat (\`/my-ai-ceo\`), the board (\`/tasks/all\`), and the
TaskModal (the "New Task" create form opened over the board). Breakpoints:
360 (mobile), 768 (tablet), 1280 (desktop). A row is a VIOLATION when
\`document.documentElement.scrollWidth > clientWidth + 1\` — the body itself
scrolls horizontally (the board's column strip is allowed its OWN internal
overflow-x container on mobile; only body-level scroll counts as a
violation).

| Surface | Breakpoint | Result | Screenshot |
| --- | --- | --- | --- |
${rows}

**${violationCount} violation(s) found** across ${catalog.length} surface x breakpoint checks.
`;
  fs.mkdirSync(PROOF_DIR, { recursive: true });
  fs.writeFileSync(`${PROOF_DIR}/VIOLATIONS.md`, body, 'utf-8');
});

/** True when the document scrolls horizontally (a responsive violation). */
async function hasHorizontalBodyScroll(page: Page): Promise<boolean> {
  return page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1);
}

async function captureAndAssert(page: Page, surface: string, bp: (typeof BREAKPOINTS)[number]): Promise<void> {
  const screenshot = `${surface}-${bp.name}.png`;
  await page.screenshot({ path: `${PROOF_DIR}/${screenshot}`, fullPage: true });
  const violated = await hasHorizontalBodyScroll(page);
  catalog.push({ surface, breakpoint: bp.name, width: bp.width, hasHorizontalScroll: violated, screenshot });
  expect(violated, `${surface} @ ${bp.name} must not scroll horizontally`).toBe(false);
}

/**
 * Fire the sanctioned interview-gate cookie setter (mirrors create-task.
 * spec.ts's unlockDashboard) so /my-ai-ceo and /tasks/all resolve instead of
 * 302-ing to /interview.
 */
async function unlockDashboard(page: Page): Promise<void> {
  await expect
    .poll(
      async () => {
        await page.goto('/interview', { waitUntil: 'domcontentloaded' });
        const check = await page.request.get('/tasks/all', { maxRedirects: 0 });
        return check.status();
      },
      {
        timeout: 30_000,
        intervals: [500, 1_000, 2_000, 3_000],
        message: 'dashboard never unlocked (interview gate cookie was never minted complete)',
      },
    )
    .toBe(200);
}

/** First-visit product walkthrough intercepts pointer events on the board;
 *  dismiss it if it renders (mirrors create-task.spec.ts). */
async function dismissWalkthroughIfPresent(page: Page): Promise<void> {
  const skip = page.getByRole('button', { name: 'Skip' });
  try {
    await skip.waitFor({ state: 'visible', timeout: 5_000 });
    await skip.click();
    await skip.waitFor({ state: 'hidden', timeout: 5_000 });
  } catch {
    // Walkthrough didn't appear — nothing to dismiss.
  }
}

/**
 * Navigate to the board past the interview gate and wait for it to render.
 * `networkidle` never resolves on /tasks/all (the board keeps an in-flight
 * polling/WebSocket connection open — see MissionQueue's live-update fetch
 * loop), so mirror create-task.spec.ts: `domcontentloaded` + wait for the
 * board's own "rendered" signal (the Backlog column) instead of network
 * activity, then dismiss the first-run walkthrough.
 */
async function gotoBoard(page: Page): Promise<void> {
  await unlockDashboard(page);
  await page.goto('/tasks/all', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('[data-walkthrough="column-backlog"]')).toBeVisible({ timeout: 15_000 });
  await dismissWalkthroughIfPresent(page);
}

/** True when the board's column-strip scroll region can scroll horizontally
 *  (i.e. its content is wider than the visible viewport). */
async function boardColumnsAreHorizontallyScrollable(page: Page): Promise<boolean | null> {
  return page.evaluate(() => {
    const region = Array.from(document.querySelectorAll('[role="region"]')).find((r) =>
      (r.getAttribute('aria-label') || '').includes('Task board columns'),
    );
    if (!region) return null;
    return region.scrollWidth > region.clientWidth + 1;
  });
}

for (const bp of BREAKPOINTS) {
  test(`My AI CEO chat has no horizontal body scroll @ ${bp.name}`, async ({ page }) => {
    await page.setViewportSize({ width: bp.width, height: bp.height });
    await unlockDashboard(page);
    await page.goto('/my-ai-ceo', { waitUntil: 'networkidle' });
    await captureAndAssert(page, 'chat', bp);
  });

  test(`Board has no horizontal body scroll @ ${bp.name}`, async ({ page }) => {
    await page.setViewportSize({ width: bp.width, height: bp.height });
    await gotoBoard(page);
    // The BODY must not scroll horizontally; the column strip scrolls INSIDE
    // its own overflow-x container (that is allowed and intended on mobile).
    await captureAndAssert(page, 'board', bp);
  });

  test(`TaskModal has no horizontal body scroll @ ${bp.name}`, async ({ page }) => {
    await page.setViewportSize({ width: bp.width, height: bp.height });
    await gotoBoard(page);
    await page.locator('[data-walkthrough="new-task"]').click();
    await expect(page.getByRole('heading', { name: 'Create New Task' })).toBeVisible();
    await captureAndAssert(page, 'modal', bp);
  });
}

/**
 * Step-4 board mobile-responsiveness (QC finding on P5-01): below `lg` the
 * board must render its columns as a horizontally-scrollable strip plus a
 * column picker, not the old full-width vertical stack that made every extra
 * column a long vertical scroll away.
 */
test('Board columns are a horizontally-scrollable strip (not a vertical stack) on mobile @ 360-mobile', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 780 });
  await gotoBoard(page);

  const scrollable = await boardColumnsAreHorizontallyScrollable(page);
  expect(scrollable).toBe(true);
});

test('Board shows a mobile column picker @ 360-mobile, hides it once every column already fits @ 1280-desktop', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 780 });
  await gotoBoard(page);

  const picker = page.getByTestId('kanban-column-picker');
  await expect(picker).toBeVisible();

  await page.setViewportSize({ width: 1280, height: 900 });
  await expect(picker).toBeHidden();
});

test('Clicking a column-picker pill scrolls the board strip to that column @ 360-mobile', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 780 });
  await gotoBoard(page);

  const region = () =>
    page.evaluate(() => {
      const r = Array.from(document.querySelectorAll('[role="region"]')).find((el) =>
        (el.getAttribute('aria-label') || '').includes('Task board columns'),
      );
      return r ? (r as HTMLElement).scrollLeft : null;
    });

  const before = await region();
  // 'done' is a fixed column id in BOARD_PRESETS.task (src/components/MissionQueue.tsx)
  // so this pill always exists regardless of seeded task data.
  await page.getByTestId('column-picker-done').click();
  await page.waitForTimeout(600); // smooth scrollIntoView
  const after = await region();

  expect(before).not.toBeNull();
  expect(after).not.toBeNull();
  expect(after as number).toBeGreaterThan(before as number);
});
