"use strict";(()=>{var e={};e.id=3495,e.ids=[3495],e.modules={5890:e=>{e.exports=require("better-sqlite3")},399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},4770:e=>{e.exports=require("crypto")},2048:e=>{e.exports=require("fs")},5315:e=>{e.exports=require("path")},2350:(e,t,a)=>{a.r(t),a.d(t,{originalPathname:()=>y,patchFetch:()=>b,requestAsyncStorage:()=>m,routeModule:()=>g,serverHooks:()=>k,staticGenerationAsyncStorage:()=>h});var i={};a.r(i),a.d(i,{GET:()=>u,POST:()=>_});var s=a(9303),o=a(8716),n=a(670),r=a(7070),d=a(4673),l=a(8890),p=a(568),c=a(4235);async function u(e){try{let{searchParams:t}=new URL(e.url),a=t.get("status"),i=t.get("business_id"),s=t.get("workspace_id"),o=t.get("assigned_agent_id"),n=`
      SELECT
        t.*,
        aa.name as assigned_agent_name,
        aa.avatar_emoji as assigned_agent_emoji,
        ca.name as created_by_agent_name
      FROM tasks t
      LEFT JOIN agents aa ON t.assigned_agent_id = aa.id
      LEFT JOIN agents ca ON t.created_by_agent_id = ca.id
      WHERE 1=1
    `,d=[];if(a){let e=a.split(",").map(e=>e.trim()).filter(Boolean);1===e.length?(n+=" AND t.status = ?",d.push(e[0])):e.length>1&&(n+=` AND t.status IN (${e.map(()=>"?").join(",")})`,d.push(...e))}i&&(n+=" AND t.business_id = ?",d.push(i)),s&&(n+=" AND t.workspace_id = ?",d.push(s)),o&&(n+=" AND t.assigned_agent_id = ?",d.push(o)),n+=" ORDER BY t.created_at DESC";let p=(0,l.Kt)(n,d).map(e=>({...e,assigned_agent:e.assigned_agent_id?{id:e.assigned_agent_id,name:e.assigned_agent_name,avatar_emoji:e.assigned_agent_emoji}:void 0}));return r.NextResponse.json(p)}catch(e){return console.error("Failed to fetch tasks:",e),r.NextResponse.json({error:"Failed to fetch tasks"},{status:500})}}async function _(e){try{let t=await e.json();console.log("[POST /api/tasks] Received body:",JSON.stringify(t));let a=c.$O.safeParse(t);if(!a.success)return r.NextResponse.json({error:"Validation failed",details:a.error.issues},{status:400});let i=a.data,s=(0,d.Z)(),o=new Date().toISOString(),n=i.workspace_id||"default",u=i.status||"backlog";(0,l.KH)(`INSERT INTO tasks (id, title, description, status, priority, assigned_agent_id, created_by_agent_id, workspace_id, business_id, due_date, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,[s,i.title,i.description||null,u,i.priority||"medium",i.assigned_agent_id||null,i.created_by_agent_id||null,n,i.business_id||"default",i.due_date||null,o,o]);let _=`New task: ${i.title}`;if(i.created_by_agent_id){let e=(0,l.pP)("SELECT name FROM agents WHERE id = ?",[i.created_by_agent_id]);e&&(_=`${e.name} created task: ${i.title}`)}(0,l.KH)(`INSERT INTO events (id, type, agent_id, task_id, message, created_at)
       VALUES (?, ?, ?, ?, ?, ?)`,[(0,d.Z)(),"task_created",t.created_by_agent_id||null,s,_,o]);let g=(0,l.pP)(`SELECT t.*,
        aa.name as assigned_agent_name,
        aa.avatar_emoji as assigned_agent_emoji,
        ca.name as created_by_agent_name,
        ca.avatar_emoji as created_by_agent_emoji
       FROM tasks t
       LEFT JOIN agents aa ON t.assigned_agent_id = aa.id
       LEFT JOIN agents ca ON t.created_by_agent_id = ca.id
       WHERE t.id = ?`,[s]);return g&&(0,p.fM)({type:"task_created",payload:g}),g&&(async()=>{try{let t=`${e.headers.get("origin")||process.env.NEXT_PUBLIC_APP_URL||"http://localhost:3000"}/api/webhooks/task-created`,a=await fetch(t,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({taskId:g.id,title:g.title,description:g.description,department:g.department,priority:g.priority,workspaceId:g.workspace_id})});a.ok?console.log("[POST /api/tasks] Webhook notification sent for task:",g.id):console.error("[POST /api/tasks] Webhook notification failed:",await a.text())}catch(e){console.error("[POST /api/tasks] Failed to trigger webhook:",e)}})(),r.NextResponse.json(g,{status:201})}catch(e){return console.error("Failed to create task:",e),r.NextResponse.json({error:"Failed to create task"},{status:500})}}let g=new s.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/tasks/route",pathname:"/api/tasks",filename:"route",bundlePath:"app/api/tasks/route"},resolvedPagePath:"/Users/blackceomacmini/projects/mission-control/src/app/api/tasks/route.ts",nextConfigOutput:"",userland:i}),{requestAsyncStorage:m,staticGenerationAsyncStorage:h,serverHooks:k}=g,y="/api/tasks/route";function b(){return(0,n.patchFetch)({serverHooks:k,staticGenerationAsyncStorage:h})}},568:(e,t,a)=>{a.d(t,{Ty:()=>o,fM:()=>n,z1:()=>s});let i=new Set;function s(e){i.add(e)}function o(e){i.delete(e)}function n(e){let t=new TextEncoder,a=`data: ${JSON.stringify(e)}

`,s=t.encode(a);for(let e of Array.from(i))try{e.enqueue(s)}catch(t){console.error("Failed to send SSE event to client:",t),i.delete(e)}console.log(`[SSE] Broadcast ${e.type} to ${i.size} client(s)`)}},4235:(e,t,a)=>{a.d(t,{$O:()=>d,_b:()=>l,kP:()=>p,th:()=>c,uR:()=>g});var i=a(6543);let s=i.KmV(["backlog","in_progress","review","blocked","done"]),o=i.KmV(["low","medium","high","critical"]),n=i.KmV(["spawned","updated","completed","file_created","status_changed"]),r=i.KmV(["file","url","artifact"]),d=i.Ryn({title:i.Z_8().min(1,"Title is required").max(500,"Title must be 500 characters or less"),description:i.Z_8().max(1e4,"Description must be 10000 characters or less").optional(),status:s.optional(),priority:o.optional(),assigned_agent_id:i.Z_8().uuid().optional(),created_by_agent_id:i.Z_8().uuid().optional(),business_id:i.Z_8().optional(),workspace_id:i.Z_8().optional(),due_date:i.Z_8().optional()}),l=i.Ryn({title:i.Z_8().min(1).max(500).optional(),description:i.Z_8().max(1e4).optional(),status:s.optional(),priority:o.optional(),assigned_agent_id:i.Z_8().uuid().optional().nullable(),due_date:i.Z_8().optional().nullable(),updated_by_agent_id:i.Z_8().uuid().optional()}),p=i.Ryn({activity_type:n,message:i.Z_8().min(1,"Message is required").max(5e3,"Message must be 5000 characters or less"),agent_id:i.Z_8().uuid().optional(),metadata:i.Z_8().optional()}),c=i.Ryn({deliverable_type:r,title:i.Z_8().min(1,"Title is required"),path:i.Z_8().optional(),description:i.Z_8().optional()}),u=[".png",".jpg",".jpeg",".svg",".webp"],_=["drive.google.com","docs.google.com","dropbox.com","dl.dropboxusercontent.com"];function g(e){let t;try{t=new URL(e)}catch{return{valid:!1,error:"That does not look like a valid URL. Please provide a full URL starting with https://"}}if("https:"!==t.protocol&&"http:"!==t.protocol)return{valid:!1,error:"Please use a URL that starts with https://"};let a=t.hostname.toLowerCase();if(_.some(e=>a===e||a.endsWith("."+e)))return a.includes("google.com")?{valid:!1,error:"Google Drive links will not work. Please use a direct image link ending in .png, .jpg, or .svg. Try uploading your image to imgur.com or your own website and sharing that link instead."}:{valid:!1,error:"Dropbox links will not work. Please use a direct image link ending in .png, .jpg, or .svg. Try uploading your image to imgur.com or your own website and sharing that link instead."};let i=t.pathname.toLowerCase();return u.some(e=>i.endsWith(e))?{valid:!0}:{valid:!1,error:`The URL must point directly to an image file. Please make sure the link ends in .png, .jpg, .jpeg, .svg, or .webp. (Your link ends with "${i.split("/").pop()||i}")`}}}};var t=require("../../../webpack-runtime.js");t.C(e);var a=e=>t(t.s=e),i=t.X(0,[8948,5972,6543,420],()=>a(2350));module.exports=i})();