"use strict";(()=>{var e={};e.id=1974,e.ids=[1974],e.modules={5890:e=>{e.exports=require("better-sqlite3")},399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},4770:e=>{e.exports=require("crypto")},2048:e=>{e.exports=require("fs")},5315:e=>{e.exports=require("path")},8798:(e,t,s)=>{s.r(t),s.d(t,{originalPathname:()=>y,patchFetch:()=>f,requestAsyncStorage:()=>E,routeModule:()=>h,serverHooks:()=>R,staticGenerationAsyncStorage:()=>k});var a={};s.r(a),s.d(a,{DELETE:()=>m,GET:()=>_,PATCH:()=>g});var i=s(9303),o=s(8716),n=s(670),r=s(7070),d=s(4673),p=s(8890),u=s(568),l=s(5844),c=s(4235);async function _(e,{params:t}){try{let{id:e}=await t,s=(0,p.pP)(`SELECT t.*,
        aa.name as assigned_agent_name,
        aa.avatar_emoji as assigned_agent_emoji
       FROM tasks t
       LEFT JOIN agents aa ON t.assigned_agent_id = aa.id
       WHERE t.id = ?`,[e]);if(!s)return r.NextResponse.json({error:"Task not found"},{status:404});return r.NextResponse.json(s)}catch(e){return console.error("Failed to fetch task:",e),r.NextResponse.json({error:"Failed to fetch task"},{status:500})}}async function g(e,{params:t}){try{let{id:s}=await t,a=await e.json(),i=c._b.safeParse(a);if(!i.success)return r.NextResponse.json({error:"Validation failed",details:i.error.issues},{status:400});let o=i.data,n=(0,p.pP)("SELECT * FROM tasks WHERE id = ?",[s]);if(!n)return r.NextResponse.json({error:"Task not found"},{status:404});let _=[],g=[],m=new Date().toISOString();if("done"===o.status&&"review"===n.status&&o.updated_by_agent_id){let e=(0,p.pP)("SELECT is_master FROM agents WHERE id = ?",[o.updated_by_agent_id]);if(!e||!e.is_master)return r.NextResponse.json({error:"Forbidden: only the master agent can approve tasks"},{status:403})}void 0!==o.title&&(_.push("title = ?"),g.push(o.title)),void 0!==o.description&&(_.push("description = ?"),g.push(o.description)),void 0!==o.priority&&(_.push("priority = ?"),g.push(o.priority)),void 0!==o.due_date&&(_.push("due_date = ?"),g.push(o.due_date));let h=!1;if(void 0!==o.status&&o.status!==n.status){_.push("status = ?"),g.push(o.status),"in_progress"===o.status&&n.assigned_agent_id&&(h=!0);let e="done"===o.status?"task_completed":"task_status_changed";(0,p.KH)(`INSERT INTO events (id, type, task_id, message, created_at)
         VALUES (?, ?, ?, ?, ?)`,[(0,d.Z)(),e,s,`Task "${n.title}" moved to ${o.status}`,m])}if(void 0!==o.assigned_agent_id&&o.assigned_agent_id!==n.assigned_agent_id&&(_.push("assigned_agent_id = ?"),g.push(o.assigned_agent_id),o.assigned_agent_id)){let e=(0,p.pP)("SELECT name FROM agents WHERE id = ?",[o.assigned_agent_id]);e&&((0,p.KH)(`INSERT INTO events (id, type, agent_id, task_id, message, created_at)
             VALUES (?, ?, ?, ?, ?, ?)`,[(0,d.Z)(),"task_assigned",o.assigned_agent_id,s,`"${n.title}" assigned to ${e.name}`,m]),("in_progress"===n.status||"in_progress"===o.status)&&(h=!0))}if(0===_.length)return r.NextResponse.json({error:"No updates provided"},{status:400});_.push("updated_at = ?"),g.push(m),g.push(s),(0,p.KH)(`UPDATE tasks SET ${_.join(", ")} WHERE id = ?`,g);let E=(0,p.pP)(`SELECT t.*,
        aa.name as assigned_agent_name,
        aa.avatar_emoji as assigned_agent_emoji,
        ca.name as created_by_agent_name,
        ca.avatar_emoji as created_by_agent_emoji
       FROM tasks t
       LEFT JOIN agents aa ON t.assigned_agent_id = aa.id
       LEFT JOIN agents ca ON t.created_by_agent_id = ca.id
       WHERE t.id = ?`,[s]);if(E&&(0,u.fM)({type:"task_updated",payload:E}),h){let e=(0,l.qN)();fetch(`${e}/api/tasks/${s}/dispatch`,{method:"POST",headers:{"Content-Type":"application/json"}}).catch(e=>{console.error("Auto-dispatch failed:",e)})}return r.NextResponse.json(E)}catch(e){return console.error("Failed to update task:",e),r.NextResponse.json({error:"Failed to update task"},{status:500})}}async function m(e,{params:t}){try{let{id:e}=await t;if(!(0,p.pP)("SELECT * FROM tasks WHERE id = ?",[e]))return r.NextResponse.json({error:"Task not found"},{status:404});return(0,p.KH)("DELETE FROM openclaw_sessions WHERE task_id = ?",[e]),(0,p.KH)("DELETE FROM events WHERE task_id = ?",[e]),(0,p.KH)("UPDATE conversations SET task_id = NULL WHERE task_id = ?",[e]),(0,p.KH)("DELETE FROM tasks WHERE id = ?",[e]),(0,u.fM)({type:"task_deleted",payload:{id:e}}),r.NextResponse.json({success:!0})}catch(e){return console.error("Failed to delete task:",e),r.NextResponse.json({error:"Failed to delete task"},{status:500})}}let h=new i.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/tasks/[id]/route",pathname:"/api/tasks/[id]",filename:"route",bundlePath:"app/api/tasks/[id]/route"},resolvedPagePath:"/Users/blackceomacmini/projects/mission-control/src/app/api/tasks/[id]/route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:E,staticGenerationAsyncStorage:k,serverHooks:R}=h,y="/api/tasks/[id]/route";function f(){return(0,n.patchFetch)({serverHooks:R,staticGenerationAsyncStorage:k})}},5844:(e,t,s)=>{function a(){return process.env.MISSION_CONTROL_URL||"http://localhost:4000"}function i(){return process.env.PROJECTS_PATH||"~/Documents/Shared/projects"}s.d(t,{nR:()=>i,qN:()=>a})},568:(e,t,s)=>{s.d(t,{Ty:()=>o,fM:()=>n,z1:()=>i});let a=new Set;function i(e){a.add(e)}function o(e){a.delete(e)}function n(e){let t=new TextEncoder,s=`data: ${JSON.stringify(e)}

`,i=t.encode(s);for(let e of Array.from(a))try{e.enqueue(i)}catch(t){console.error("Failed to send SSE event to client:",t),a.delete(e)}console.log(`[SSE] Broadcast ${e.type} to ${a.size} client(s)`)}},4235:(e,t,s)=>{s.d(t,{$O:()=>d,_b:()=>p,kP:()=>u,th:()=>l,uR:()=>g});var a=s(6543);let i=a.KmV(["backlog","in_progress","review","blocked","done"]),o=a.KmV(["low","medium","high","critical"]),n=a.KmV(["spawned","updated","completed","file_created","status_changed"]),r=a.KmV(["file","url","artifact"]),d=a.Ryn({title:a.Z_8().min(1,"Title is required").max(500,"Title must be 500 characters or less"),description:a.Z_8().max(1e4,"Description must be 10000 characters or less").optional(),status:i.optional(),priority:o.optional(),assigned_agent_id:a.Z_8().uuid().optional(),created_by_agent_id:a.Z_8().uuid().optional(),business_id:a.Z_8().optional(),workspace_id:a.Z_8().optional(),due_date:a.Z_8().optional()}),p=a.Ryn({title:a.Z_8().min(1).max(500).optional(),description:a.Z_8().max(1e4).optional(),status:i.optional(),priority:o.optional(),assigned_agent_id:a.Z_8().uuid().optional().nullable(),due_date:a.Z_8().optional().nullable(),updated_by_agent_id:a.Z_8().uuid().optional()}),u=a.Ryn({activity_type:n,message:a.Z_8().min(1,"Message is required").max(5e3,"Message must be 5000 characters or less"),agent_id:a.Z_8().uuid().optional(),metadata:a.Z_8().optional()}),l=a.Ryn({deliverable_type:r,title:a.Z_8().min(1,"Title is required"),path:a.Z_8().optional(),description:a.Z_8().optional()}),c=[".png",".jpg",".jpeg",".svg",".webp"],_=["drive.google.com","docs.google.com","dropbox.com","dl.dropboxusercontent.com"];function g(e){let t;try{t=new URL(e)}catch{return{valid:!1,error:"That does not look like a valid URL. Please provide a full URL starting with https://"}}if("https:"!==t.protocol&&"http:"!==t.protocol)return{valid:!1,error:"Please use a URL that starts with https://"};let s=t.hostname.toLowerCase();if(_.some(e=>s===e||s.endsWith("."+e)))return s.includes("google.com")?{valid:!1,error:"Google Drive links will not work. Please use a direct image link ending in .png, .jpg, or .svg. Try uploading your image to imgur.com or your own website and sharing that link instead."}:{valid:!1,error:"Dropbox links will not work. Please use a direct image link ending in .png, .jpg, or .svg. Try uploading your image to imgur.com or your own website and sharing that link instead."};let a=t.pathname.toLowerCase();return c.some(e=>a.endsWith(e))?{valid:!0}:{valid:!1,error:`The URL must point directly to an image file. Please make sure the link ends in .png, .jpg, .jpeg, .svg, or .webp. (Your link ends with "${a.split("/").pop()||a}")`}}}};var t=require("../../../../webpack-runtime.js");t.C(e);var s=e=>t(t.s=e),a=t.X(0,[8948,5972,6543,420],()=>s(8798));module.exports=a})();