/**
 * Output Buckets , cross-agent type-based file aggregation.
 *
 * Track B3 / SCOPE-ADDITION Addition 2.
 *
 * The Workspace UI lets the operator switch between two views:
 *
 *   "By Agent" , files grouped by the owning agent (see aggregator.ts).
 *   "By Type"  , files grouped into 7 output buckets (this module).
 *
 * The 7 buckets:
 *
 *   1. All Images       (.png .jpg .jpeg .webp .gif .svg .avif)
 *   2. All Videos       (.mp4 .webm .mov .m4v .mkv)
 *   3. All Audio        (.mp3 .wav .ogg .m4a .aac .flac)
 *   4. All Apps         (any directory containing index.html, served as a unit)
 *   5. All Documents    (.md .markdown .pdf .txt)
 *   6. All Code         (.ts .tsx .js .py .sh .json .yaml, plus a few more)
 *   7. All Searches     (saved research markdown from `research_searches` table,
 *                        mirrored to `<vault>/research/YYYY/MM/...`)
 *
 * Sources walked:
 *   - Every per-agent scratch directory (via aggregator.walkAllAgents)
 *   - `<vault>/studio/` (Track B4 outputs)
 *   - `<vault>/research/` (Track B7 outputs, also seen via research_searches)
 *
 * The "All Searches" bucket is read from the `research_searches` table.
 * Track B7 owns the write side of that table; this module is read-only.
 */

import { readdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { vaultRoot } from '@/lib/platform';
import {
  classifyFile,
  walkAllAgents,
  type AgentScratch,
  type OperatorAgent,
  type WorkspaceFile,
  type WorkspaceFileKind,
} from './aggregator';
import { listResearchSearches } from '@/lib/research-store';

export type BucketId =
  | 'images'
  | 'videos'
  | 'audio'
  | 'apps'
  | 'documents'
  | 'code'
  | 'searches';

export interface BucketDescriptor {
  id: BucketId;
  label: string;
  description: string;
}

export const BUCKETS: BucketDescriptor[] = [
  { id: 'images', label: 'All Images', description: 'Every image rendered across agents, studio, and research.' },
  { id: 'videos', label: 'All Videos', description: 'HyperFrames renders, studio video output, captures.' },
  { id: 'audio', label: 'All Audio', description: 'Voice clones, TTS output, generated tracks.' },
  { id: 'apps', label: 'All Apps', description: 'Directories containing an index.html ready to preview.' },
  { id: 'documents', label: 'All Documents', description: 'Markdown notes, PDFs, plain text files.' },
  { id: 'code', label: 'All Code', description: 'Scripts and source files generated by the agents.' },
  { id: 'searches', label: 'All Searches', description: 'Saved Research results (xAI Live Search).' },
];

/**
 * Universal source label for a file: an agent slug, or one of the vault
 * sub-folders that contribute to buckets without belonging to a CLI agent.
 */
export type BucketSource = OperatorAgent | 'studio' | 'research';

export interface BucketItem {
  /** Bucket this item belongs to. */
  bucket: BucketId;
  /** Owning agent or vault source. */
  source: BucketSource;
  /** Filename. */
  name: string;
  /** Path relative to the source's root (forward slashes on every OS). */
  relPath: string;
  /** Size in bytes. */
  bytes: number;
  /** Last modified ms since epoch. */
  mtime: number;
  /** Classifier kind from aggregator (matches bucket where possible). */
  kind: WorkspaceFileKind;
  /** Lowercase extension. */
  ext: string;
  /**
   * URL the UI uses to fetch the file. For agent-rooted files this is the
   * workspace file API; for vault-rooted files this is a vault file API
   * (Track B6 owns the vault file API; until that lands the UI shows
   * metadata only for vault sources).
   */
  fileUrl: string;
  /**
   * Optional thumbnail/preview URL. For images this is the same as fileUrl.
   * For videos it points at the file itself; the browser handles a poster
   * frame via a `<video preload="metadata">` tag.
   */
  thumbUrl?: string;
  /** Extra metadata. Used by "searches" to surface the original query. */
  extra?: Record<string, unknown>;
}

export interface BucketSummary {
  id: BucketId;
  label: string;
  description: string;
  count: number;
  /** Most recent mtime (ms epoch) across the bucket, used for sort+freshness UX. */
  latest: number | null;
}

export interface BucketsListing {
  summary: BucketSummary[];
  /** Optional: bucket items keyed by bucket id. Only present when `bucketId` is requested. */
  items?: BucketItem[];
  /** Total across all buckets (sum of summary.count). */
  total: number;
}

/**
 * Map a WorkspaceFile kind / extension to a bucket id. Returns null when
 * the file does not belong to any bucket (e.g. a `.zip` binary).
 *
 * The "apps" bucket is NOT covered here because it operates on directories,
 * not individual files; see `collectApps()`.
 */
function fileToBucket(file: { kind: WorkspaceFileKind; ext: string }): BucketId | null {
  switch (file.kind) {
    case 'image':
      return 'images';
    case 'video':
      return 'videos';
    case 'audio':
      return 'audio';
    case 'markdown':
      return 'documents';
    case 'pdf':
      return 'documents';
    case 'text':
      // .txt is a document; everything else text-flagged falls through to code.
      if (file.ext === '.txt') return 'documents';
      return 'code';
    case 'code':
      return 'code';
    default:
      return null;
  }
}

function buildAgentFileUrl(agent: OperatorAgent, relPath: string): string {
  const qs = new URLSearchParams({ agent, path: relPath });
  return `/api/operator/workspace/file?${qs.toString()}`;
}

/**
 * Build a vault file URL for studio/research sources. The Track B6 vault
 * file API is not part of this track; we use a placeholder route under the
 * operator API namespace that B6 can implement. Until then, the link falls
 * back to a download-style absolute path that the UI can render as a label
 * only (it will not 200, but the metadata listing still renders).
 */
function buildVaultFileUrl(source: 'studio' | 'research', relPath: string): string {
  const qs = new URLSearchParams({ source, path: relPath });
  return `/api/operator/vault/file?${qs.toString()}`;
}

/**
 * Walk a vault sub-folder and yield workspace-style records. Used for
 * `studio/` and `research/` which contribute to buckets but are not owned
 * by any CLI agent.
 */
async function walkVaultSubdir(sub: 'studio' | 'research'): Promise<WorkspaceFile[]> {
  const root = path.join(vaultRoot(), sub);
  if (!existsSync(root)) return [];
  const out: WorkspaceFile[] = [];
  async function walk(dir: string, depth: number): Promise<void> {
    if (depth > 6 || out.length >= 1000) return;
    let items;
    try {
      items = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const it of items) {
      if (out.length >= 1000) break;
      if (it.name === '.git' || it.name === 'node_modules') continue;
      const full = path.join(dir, it.name);
      if (it.isDirectory()) {
        await walk(full, depth + 1);
      } else if (it.isFile()) {
        let st;
        try {
          st = await stat(full);
        } catch {
          continue;
        }
        const { kind, ext } = classifyFile(it.name);
        const rel = path.relative(root, full).split(path.sep).join('/');
        out.push({
          name: it.name,
          relPath: rel,
          // Tag with the vault source so downstream code can pick the right URL builder.
          // `agent` is reused here as a generic "source" tag; consumers check it.
          agent: sub as unknown as OperatorAgent,
          absPath: full,
          bytes: st.size,
          mtime: st.mtimeMs,
          kind,
          ext,
        });
      }
    }
  }
  await walk(root, 0);
  return out;
}

/**
 * Detect "app" directories (any directory containing index.html) across all
 * agent scratch roots. Apps are surfaced as a single entry per directory
 * so the UI can link straight to a preview.
 */
function collectApps(allAgents: AgentScratch[]): BucketItem[] {
  const apps: BucketItem[] = [];
  for (const scratch of allAgents) {
    if (!scratch.exists) continue;
    // Group files by their parent directory and look for an index.html.
    const byDir = new Map<string, WorkspaceFile[]>();
    for (const f of scratch.files) {
      const parent = f.relPath.includes('/') ? f.relPath.split('/').slice(0, -1).join('/') : '';
      if (!byDir.has(parent)) byDir.set(parent, []);
      byDir.get(parent)!.push(f);
    }
    byDir.forEach((files, dir) => {
      const index = files.find((f: WorkspaceFile) => f.name.toLowerCase() === 'index.html');
      if (!index) return;
      apps.push({
        bucket: 'apps',
        source: scratch.agent,
        name: dir ? dir.split('/').pop() || dir : index.name,
        relPath: dir || index.relPath,
        bytes: index.bytes,
        mtime: index.mtime,
        kind: 'app',
        ext: '.html',
        fileUrl: buildAgentFileUrl(scratch.agent, index.relPath),
        extra: { fileCount: files.length, indexRelPath: index.relPath },
      });
    });
  }
  apps.sort((a, b) => b.mtime - a.mtime);
  return apps;
}

function workspaceFileToBucketItem(file: WorkspaceFile, source: BucketSource): BucketItem | null {
  const bucket = fileToBucket(file);
  if (!bucket) return null;
  const isVaultSource = source === 'studio' || source === 'research';
  const fileUrl = isVaultSource
    ? buildVaultFileUrl(source, file.relPath)
    : buildAgentFileUrl(source as OperatorAgent, file.relPath);
  const thumbUrl = file.kind === 'image' || file.kind === 'video' ? fileUrl : undefined;
  return {
    bucket,
    source,
    name: file.name,
    relPath: file.relPath,
    bytes: file.bytes,
    mtime: file.mtime,
    kind: file.kind,
    ext: file.ext,
    fileUrl,
    thumbUrl,
  };
}

/**
 * Collect every bucket item across every source. Heavy operation: walks
 * the entire scratch tree plus two vault sub-trees plus the research_searches
 * table. Cache the result at the route level if call volume warrants it.
 */
export async function collectAllBuckets(): Promise<BucketItem[]> {
  const [agentScratches, studioFiles, researchFiles] = await Promise.all([
    walkAllAgents(),
    walkVaultSubdir('studio'),
    walkVaultSubdir('research'),
  ]);

  const items: BucketItem[] = [];

  for (const scratch of agentScratches) {
    if (!scratch.exists) continue;
    for (const f of scratch.files) {
      const item = workspaceFileToBucketItem(f, scratch.agent);
      if (item) items.push(item);
    }
  }

  for (const f of studioFiles) {
    const item = workspaceFileToBucketItem(f, 'studio');
    if (item) items.push(item);
  }
  for (const f of researchFiles) {
    const item = workspaceFileToBucketItem(f, 'research');
    if (item) items.push(item);
  }

  // App directories.
  items.push(...collectApps(agentScratches));

  // All Searches: pulled from the research_searches table (Track B7).
  try {
    const searches = listResearchSearches({ limit: 200, offset: 0 });
    for (const row of searches.items) {
      items.push({
        bucket: 'searches',
        source: 'research',
        name: row.query.length > 60 ? row.query.slice(0, 57) + '...' : row.query,
        relPath: row.id,
        bytes: row.result_markdown.length,
        mtime: new Date(row.created_at).getTime() || Date.now(),
        kind: 'markdown',
        ext: '.md',
        fileUrl: `/api/operator/research/${row.id}`,
        extra: {
          query: row.query,
          model: row.model,
          created_at: row.created_at,
        },
      });
    }
  } catch {
    // research_searches table may not exist yet on a fresh database; degrade silently.
  }

  // Newest first across the board.
  items.sort((a, b) => b.mtime - a.mtime);
  return items;
}

export interface ListBucketsOptions {
  /** When provided, restrict items to this bucket. */
  bucketId?: BucketId;
  /** Pagination (only honored when bucketId is set). */
  limit?: number;
  offset?: number;
}

/**
 * Build the buckets summary and (optionally) the paginated item list for a
 * single bucket. The summary always covers all 7 buckets.
 */
export async function listBuckets(opts: ListBucketsOptions = {}): Promise<BucketsListing> {
  const all = await collectAllBuckets();

  const byBucket = new Map<BucketId, BucketItem[]>();
  for (const b of BUCKETS) byBucket.set(b.id, []);
  for (const it of all) {
    const bucket = byBucket.get(it.bucket);
    if (bucket) bucket.push(it);
  }

  const summary: BucketSummary[] = BUCKETS.map((b) => {
    const list = byBucket.get(b.id) || [];
    const latest = list.reduce<number | null>((acc, it) => (acc === null || it.mtime > acc ? it.mtime : acc), null);
    return {
      id: b.id,
      label: b.label,
      description: b.description,
      count: list.length,
      latest,
    };
  });

  let items: BucketItem[] | undefined;
  if (opts.bucketId) {
    const list = byBucket.get(opts.bucketId) || [];
    const rawLimit = typeof opts.limit === 'number' ? opts.limit : 60;
    const rawOffset = typeof opts.offset === 'number' ? opts.offset : 0;
    const limit = Math.max(1, Math.min(200, Math.floor(rawLimit)));
    const offset = Math.max(0, Math.floor(rawOffset));
    items = list.slice(offset, offset + limit);
  }

  return {
    summary,
    items,
    total: summary.reduce((acc, s) => acc + s.count, 0),
  };
}

/** Narrow a raw string into a BucketId or return null. */
export function parseBucketId(input: string | null | undefined): BucketId | null {
  if (!input) return null;
  const lower = input.toLowerCase();
  return (BUCKETS.find((b) => b.id === lower)?.id ?? null) as BucketId | null;
}
