"use strict";(()=>{var e={};e.id=7233,e.ids=[7233],e.modules={5890:e=>{e.exports=require("better-sqlite3")},399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},4770:e=>{e.exports=require("crypto")},2048:e=>{e.exports=require("fs")},5315:e=>{e.exports=require("path")},1903:(e,t,s)=>{s.r(t),s.d(t,{originalPathname:()=>v,patchFetch:()=>T,requestAsyncStorage:()=>E,routeModule:()=>g,serverHooks:()=>l,staticGenerationAsyncStorage:()=>m});var a={};s.r(a),s.d(a,{GET:()=>_,POST:()=>c});var n=s(9303),r=s(8716),o=s(670),i=s(7070),d=s(4673),p=s(4770),u=s(8890);async function c(e){try{let t=await e.text();if(process.env.WEBHOOK_SECRET){let s=e.headers.get("x-webhook-signature");if(!s||!function(e,t){let s=process.env.WEBHOOK_SECRET;return!s||!!e&&e===(0,p.createHmac)("sha256",s).update(t).digest("hex")}(s,t))return console.warn("[WEBHOOK] Invalid signature attempt"),i.NextResponse.json({error:"Unauthorized"},{status:401})}let s=JSON.parse(t),a=new Date().toISOString();if(s.task_id){let e=(0,u.pP)(`SELECT t.*, a.name as assigned_agent_name
         FROM tasks t
         LEFT JOIN agents a ON t.assigned_agent_id = a.id
         WHERE t.id = ?`,[s.task_id]);if(!e)return i.NextResponse.json({error:"Task not found"},{status:404});return"review"!==e.status&&"done"!==e.status&&(0,u.KH)("UPDATE tasks SET status = ?, updated_at = ? WHERE id = ?",["review",a,e.id]),(0,u.KH)(`INSERT INTO events (id, type, agent_id, task_id, message, created_at)
         VALUES (?, ?, ?, ?, ?, ?)`,[(0,d.Z)(),"task_completed",e.assigned_agent_id,e.id,`${e.assigned_agent_name} completed: ${s.summary||"Task finished"}`,a]),e.assigned_agent_id&&(0,u.KH)("UPDATE agents SET status = ?, updated_at = ? WHERE id = ?",["standby",a,e.assigned_agent_id]),i.NextResponse.json({success:!0,task_id:e.id,new_status:"review",message:"Task moved to review for verification"})}if(s.session_id&&s.message){let e=s.message.match(/TASK_COMPLETE:\s*(.+)/i);if(!e)return i.NextResponse.json({error:"Invalid completion message format. Expected: TASK_COMPLETE: [summary]"},{status:400});let t=e[1].trim(),n=(0,u.pP)("SELECT * FROM openclaw_sessions WHERE openclaw_session_id = ? AND status = ?",[s.session_id,"active"]);if(!n)return i.NextResponse.json({error:"Session not found or inactive"},{status:404});let r=(0,u.pP)(`SELECT t.*, a.name as assigned_agent_name
         FROM tasks t
         LEFT JOIN agents a ON t.assigned_agent_id = a.id
         WHERE t.assigned_agent_id = ?
           AND t.status = 'in_progress'
         ORDER BY t.updated_at DESC
         LIMIT 1`,[n.agent_id]);if(!r)return i.NextResponse.json({error:"No active task found for this agent"},{status:404});return"review"!==r.status&&"done"!==r.status&&(0,u.KH)("UPDATE tasks SET status = ?, updated_at = ? WHERE id = ?",["review",a,r.id]),(0,u.KH)(`INSERT INTO events (id, type, agent_id, task_id, message, created_at)
         VALUES (?, ?, ?, ?, ?, ?)`,[(0,d.Z)(),"task_completed",n.agent_id,r.id,`${r.assigned_agent_name} completed: ${t}`,a]),(0,u.KH)("UPDATE agents SET status = ?, updated_at = ? WHERE id = ?",["standby",a,n.agent_id]),i.NextResponse.json({success:!0,task_id:r.id,agent_id:n.agent_id,summary:t,new_status:"review",message:"Task moved to review for verification"})}return i.NextResponse.json({error:"Invalid payload. Provide either task_id or session_id + message"},{status:400})}catch(e){return console.error("Agent completion webhook error:",e),i.NextResponse.json({error:"Internal server error"},{status:500})}}async function _(){try{let e=(0,u.Kt)(`SELECT e.*, a.name as agent_name, t.title as task_title
       FROM events e
       LEFT JOIN agents a ON e.agent_id = a.id
       LEFT JOIN tasks t ON e.task_id = t.id
       WHERE e.type = 'task_completed'
       ORDER BY e.created_at DESC
       LIMIT 10`);return i.NextResponse.json({status:"active",recent_completions:e,endpoint:"/api/webhooks/agent-completion"})}catch(e){return console.error("Failed to fetch completion status:",e),i.NextResponse.json({error:"Failed to fetch status"},{status:500})}}let g=new n.AppRouteRouteModule({definition:{kind:r.x.APP_ROUTE,page:"/api/webhooks/agent-completion/route",pathname:"/api/webhooks/agent-completion",filename:"route",bundlePath:"app/api/webhooks/agent-completion/route"},resolvedPagePath:"/Users/blackceomacmini/projects/mission-control/src/app/api/webhooks/agent-completion/route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:E,staticGenerationAsyncStorage:m,serverHooks:l}=g,v="/api/webhooks/agent-completion/route";function T(){return(0,o.patchFetch)({serverHooks:l,staticGenerationAsyncStorage:m})}}};var t=require("../../../../webpack-runtime.js");t.C(e);var s=e=>t(t.s=e),a=t.X(0,[8948,5972,420],()=>s(1903));module.exports=a})();